project_name: dirdump
release:
  github:
    owner: youngnick
    name: dirdump
builds:
  - id: dirdump
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/youngnick/dirdump/pkg/version.version=
archives:
  - id: dirdump
    builds:
    - dirdump
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
