apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: dirdump
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/youngnick/dirdump/releases/download/v0.1.0/dirdump_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./dirdump"
      to: "."
    - from: LICENSE
      to: "."
    bin: "dirdump"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/youngnick/dirdump/releases/download/v0.1.0/dirdump_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./dirdump"
      to: "."
    - from: LICENSE
      to: "."
    bin: "dirdump"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/youngnick/dirdump/releases/download/v0.1.0/dirdump_windows_amd64.zip
    sha256: ""
    files:
    - from: "/dirdump.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "dirdump.exe"
  shortDescription: A new plugin
  homepage: https://github.com/youngnick/dirdump
  caveats: |
    Usage:
      $ kubectl dirdump

    For additional options:
      $ kubectl dirdump --help
      or https://github.com/youngnick/dirdump/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
