apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: cfgmap
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/youngnick/cfgmap/releases/download/v0.1.0/cfgmap_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./cfgmap"
      to: "."
    - from: LICENSE
      to: "."
    bin: "cfgmap"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/youngnick/cfgmap/releases/download/v0.1.0/cfgmap_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./cfgmap"
      to: "."
    - from: LICENSE
      to: "."
    bin: "cfgmap"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/youngnick/cfgmap/releases/download/v0.1.0/cfgmap_windows_amd64.zip
    sha256: ""
    files:
    - from: "/cfgmap.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "cfgmap.exe"
  shortDescription: A new plugin
  homepage: https://github.com/youngnick/cfgmap
  caveats: |
    Usage:
      $ kubectl cfgmap

    For additional options:
      $ kubectl cfgmap --help
      or https://github.com/youngnick/cfgmap/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
