apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: directory
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/youngnick/directory/releases/download/v0.1.0/directory_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./directory"
      to: "."
    - from: LICENSE
      to: "."
    bin: "directory"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/youngnick/directory/releases/download/v0.1.0/directory_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./directory"
      to: "."
    - from: LICENSE
      to: "."
    bin: "directory"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/youngnick/directory/releases/download/v0.1.0/directory_windows_amd64.zip
    sha256: ""
    files:
    - from: "/directory.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "directory.exe"
  shortDescription: A new plugin
  homepage: https://github.com/youngnick/directory
  caveats: |
    Usage:
      $ kubectl directory

    For additional options:
      $ kubectl directory --help
      or https://github.com/youngnick/directory/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
